In [1]:
import pandas as pd
import numpy as np

In [2]:
orders = pd.DataFrame({
    'order_id':[1,2,3,4,5],
    'store':['강남','잠실','강남','홍대','강남'],
    'amount':[10000, 20000, 15000, 30000, 25000]
})

In [3]:
store_count = orders['store'].value_counts()
store_count

store
강남    3
잠실    1
홍대    1
Name: count, dtype: int64

In [4]:
# 매장별 주문 건수화 총금액 함께 집계
orders.groupby('store').agg(order_count=('order_id','count'), total_amount=('amount','sum')).reset_index()

  store  order_count  total_amount
0    강남            3         50000
1    잠실            1         20000
2    홍대            1         30000

In [5]:
# 고객 데이터
customers = pd.DataFrame({
    'customer_id':[101,102,103],
    'customer_name':['앨리스','밥','캐롤']
})

In [6]:
orders = pd.DataFrame({
    'order_id':[1,2,3,4,5],
    'store':['강남','잠실','강남','홍대','강남'],
    'amount':[10000, 20000, 15000, 30000, 25000],
    'customer_id':[101,102,104,np.nan,np.nan]
})
orders

   order_id store  amount  customer_id
0         1    강남   10000        101.0
1         2    잠실   20000        102.0
2         3    강남   15000        104.0
3         4    홍대   30000          NaN
4         5    강남   25000          NaN

In [7]:
# merge
inner_join = pd.merge(orders, customers, on='customer_id', how='inner')
inner_join

   order_id store  amount  customer_id customer_name
0         1    강남   10000        101.0           앨리스
1         2    잠실   20000        102.0             밥

In [8]:
left_join = orders.merge(customers, on='customer_id', how='left')
left_join

   order_id store  amount  customer_id customer_name
0         1    강남   10000        101.0           앨리스
1         2    잠실   20000        102.0             밥
2         3    강남   15000        104.0           NaN
3         4    홍대   30000          NaN           NaN
4         5    강남   25000          NaN           NaN

In [9]:
df = pd.read_csv('Titanic-Dataset.csv')
df.shape

(891, 12)

In [10]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [11]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    str
 4   Sex          891 non-null    str
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    str
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    str
 11  Embarked     889 non-null    str
dtypes: float64(2), int64(5), str(5)
memory usage: 83.7 KB

In [12]:
df.describe()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

In [13]:
missing_count = df.isnull().sum()
missing_count[['Age','Cabin','Embarked']]
missing_value = df.isnull().sum()/len(df)
missing_value[['Age','Cabin','Embarked']].round(3)*100

Age         19.9
Cabin       77.1
Embarked     0.2
dtype: float64

In [14]:
df['Age'] =df['Age'].fillna(df['Age'].median())

In [15]:
df['Sex'] = df['Sex'].map(lambda x: 1 if x =='female' else 0)
df['Sex'].value_counts()

Sex
0    577
1    314
Name: count, dtype: int64

In [16]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    str
 4   Sex          891 non-null    int64
 5   Age          891 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    str
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    str
 11  Embarked     889 non-null    str
dtypes: float64(2), int64(6), str(4)
memory usage: 83.7 KB

In [17]:
df_cabin = df['Cabin'].str[0]
df_cabin.value_counts()

Cabin
C    59
B    47
D    33
E    32
A    15
F    13
G     4
T     1
Name: count, dtype: int64

In [20]:
# 순서가 없는 범주형 데이터
sample_df = pd.DataFrame({
    'Embarked':['S','C','Q','S'],
    'membership':['basic','premium','vip','basic']
})
sample_df

  Embarked membership
0        S      basic
1        C    premium
2        Q        vip
3        S      basic

In [21]:
# 원핫 인코딩
embarked_one_hot = pd.get_dummies(sample_df['Embarked'], prefix='emb', dtype=int)
embarked_one_hot

   emb_C  emb_Q  emb_S
0      0      0      1
1      1      0      0
2      0      1      0
3      0      0      1

In [22]:
!uv pip install scikit-learn

Resolved 5 packages in 235ms
Downloading scikit-learn (7.6MiB)
Downloading scipy (34.9MiB)
 Downloaded scikit-learn
 Downloaded scipy
Prepared 4 packages in 1.23s
Installed 4 packages in 2.40s
 + joblib==1.5.3
 + scikit-learn==1.8.0
 + scipy==1.17.1
 + threadpoolctl==3.6.0

In [24]:
from sklearn.preprocessing import LabelEncoder

Le = LabelEncoder()

In [25]:
membership_label = Le.fit_transform(sample_df['membership'])
membership_label

array([0, 1, 2, 0])

In [26]:
# StandardScaler : 평균 0, 표준편차 1 -> (값 - 평균) / 표준편차 
# MinMaxScler : 0 ~ 1 사이의 값 (양수만 존재)
# RobustScaler : 중앙값과 IQR을 사용, 이상치에 영향을 덜 받지만 연산량 많음
# 음수 표현이 의미가 있을 경우 StandardScaler 사용 등, 스케일링시 도메인 지식 필요

from sklearn.preprocessing import StandardScaler, MinMaxScaler, RobustScaler
scaler = StandardScaler()

In [30]:
age_df = pd.DataFrame({'Age':[20,30,40]})
age_scaled = scaler.fit_transform(age_df[['Age']]) # 데이터프레임 형식으로 전달 
result_df = pd.DataFrame({'Age_original':age_df['Age'],'Age_scaled':age_scaled.flatten().round(2)})
result_df

   Age_original  Age_scaled
0            20       -1.22
1            30        0.00
2            40        1.22

In [34]:
scaler = MinMaxScaler()
fare_df = pd.DataFrame({'Age':[10,60,110]})
fare_scaled = scaler.fit_transform(fare_df[['Age']])
result_df = pd.DataFrame({'Fare_original':fare_df['Age'],'Fare_scaled':fare_scaled.flatten().round(2)})
result_df

   Fare_original  Fare_scaled
0             10          0.0
1             60          0.5
2            110          1.0

In [ ]:
robust_scaler = RobustScaler()
standard_scaler = StandardScaler()
fare_df = pd.DataFrame({'fare':[7.25,7.92,53.10,71.83,512.00]})

standard_values = standard_scaler.fit_transform(fare_df[['fare']])
robust_values = robust_scaler.fit_transform(fare_df[['fare']])
result_df = pd.DataFrame({'standard_values':standard_values.flatten().round(2),'robust_values':robust_values.flatten().round(2)})
result_df

   standard_values  robust_values
0            -0.64          -0.72
1            -0.64          -0.71
2            -0.40           0.00
3            -0.30           0.29
4             1.98           7.18

In [36]:
telco_df = pd.read_csv("WA_Fn-UseC_-Telco-Customer-Churn.csv")
telco_df.shape

(7043, 21)

In [42]:
# 문자형 열만 골라내기
categorical_cols = telco_df.select_dtypes(include='str').columns.tolist()
categorical_cols
# 숫자형 열만 골라내기
numeric_cols = telco_df.select_dtypes(exclude='str').columns.tolist()
numeric_cols

['SeniorCitizen', 'tenure', 'MonthlyCharges']

In [46]:
contract_rate = telco_df.groupby('Contract')['Churn'].value_counts().rename('ratio').reset_index()
contract_rate

         Contract Churn  ratio
0  Month-to-month    No   2220
1  Month-to-month   Yes   1655
2        One year    No   1307
3        One year   Yes    166
4        Two year    No   1647
5        Two year   Yes     48

In [51]:
# 학습데이터와 테스트 데이터 분리
from sklearn.model_selection import train_test_split

sample_df = pd.DataFrame({
    'feature_a': range(10),
    'Churn':[0,0,0,0,0,0,0,1,1,1]
})

X = sample_df[['feature_a']]
y = sample_df['Churn']

X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.2, random_state=42, stratify=y)
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((8, 1), (2, 1), (8,), (2,))